### PR TITLE
Fix: InstanceId Report

### LINKED ISSUE #2831: Descarga de Reporte Balance de Prueba no toma última consulta sino la primera
## Bug report

Al descargar datos de un reporte de balance de prueba, se descargan datos de la primer consulta y no del último reporte que estoy visualizando.

[report_engine_5856831011652286333.xlsx](https://github.com/user-attachments/files/17422923/report_engine_5856831011652286333.xlsx)

#### Steps to reproduce

1. Se genera una consulta de un balance de preuba para un período determinado y una cuenta (12110) 
2. Se ve q no tiene micha info, se va a los parámetros laterales y se amplia la fecha de la consulta. 
3. Se visualizan muchos registros. 
4. Se descarga vista.
5. el excel tiene sólo los registros de la primer consulta.

Parámetros
Organización: Agencia sa
Cuenta: 12110
Fechas: 1/1/2023 - 20/11/2024

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/80ef9738-6eec-4615-9e2d-938e1abf6112

#### Other relevant information
- Instancia: 24814
- Web Browser:
- Node.js version:
- adempiere-vue version:  4.4.020-rc-2

### PR DESCRIPTION
**Pull request by Ricargame**
#### Screenshot or Gif

https://github.com/user-attachments/assets/457d5a47-80bc-409e-bca2-97235c4d0d72

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- Yarn version:
- adempiere-vue version: 

#### Additional context
fixes: https://github.com/solop-develop/frontend-core/issues/2831

### CODE REVIEW

File: src/store/modules/ADempiere/reportManager.js [hunk 1]
```diff
@@ -77,12 +77,16 @@ const initState = {
   contactSend: '',
   typeNotify: '',
   defaultBody: '',
-  activateCollapse: 0
+  activateCollapse: 0,
+  instanceId: ''
```
Comment (yamelsenih) [inline src/store/modules/ADempiere/reportManager.js]: La instancia es del tipo **Entero**

**Review by yamelsenih — CHANGES_REQUESTED** [review]

**Review by yamelsenih — APPROVED** [review]

**Review by EdwinBetanc0urt — APPROVED** [review]
