### PR TITLE
Fix: Side tab, accounting information tab does not show any information

### LINKED ISSUE #1835: Pestaña lateral, solapa informacion contable no muestra ninguna info
## Bug report
Entrando a la pestaña lateral, en la solapa información contable no se visualiza ninguna información en VUE.
En zk, con el mismo documento se visualiza ok

#### Steps to reproduce

1. [consultar registro]
2. [consultar información contable]

#### Screenshot or Gif（截图或动态图）
En VUE
image (4)

En zk
image (5)

#### Expected behavior
Poder visualizar la información contable del registro

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:
instancia 24157
Rol administrador
Org sucursal este
Orden de compra 10766

### PR DESCRIPTION
**Pull request by elsiosanchez**
### **_Screenshot or Gif_**

https://github.com/solop-develop/frontend-core/assets/45974454/547b6632-0883-4842-9ff1-bad45a3c3c28

### **_Issues_**

Fixed: #1835

### CODE REVIEW

File: src/components/ADempiere/TabManager/AdvancedTabQuery.vue [hunk 1]
```diff
@@ -333,6 +333,17 @@ export default defineComponent({
...
         isAdvancedQuery: true
       })
+        .then(response => {
+          const currentRoute = router.app._route
+          const { query } = currentRoute
+          const { tableName } = store.getters.getStoredTab(props.parentUuid, props.containerUuid)
+          router.replace({
+            query: {
+              ...query,
+              recordId: response[0][tableName + '_ID']
```
Comment (EdwinBetanc0urt) [inline src/components/ADempiere/TabManager/AdvancedTabQuery.vue]: Please evaluate if the record is empty, and the action evaluates which is the uuid of the record to be established as current, the set in the path should be added there

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]

File: src/components/ADempiere/TabManager/AdvancedTabQuery.vue (hunk 1 above)
Comment (elsiosanchez) [reply src/components/ADempiere/TabManager/AdvancedTabQuery.vue]: https://github.com/solop-develop/frontend-core/pull/1868/commits/7e237171b3b0ee774ece67a8c78b40f79b97b32c

**Review by EdwinBetanc0urt — APPROVED** [review]
