### PR TITLE
Fix: Hidden Arrow Report Enginer

### LINKED ISSUE #2782: Flechita para aumentar detalle en línea de Informe Financiero de Cuenta Contable
Flecha para aumentar detalle que no se comprende lógica.

image

Si no tiene nada para aumentar detalle, no debería mostarse ninguna flechita para abajo

Validado con los siguientes parámetros

Instancia 24814
image

### PR DESCRIPTION
**Pull request by Ricargame**
## Bug report / Feature

**Before**

imagen

**After**

imagen

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- Yarn version:
- adempiere-vue version: 

#### Additional context
fixes: https://github.com/solop-develop/frontend-core/issues/2782

### CODE REVIEW

**Review by EdwinBetanc0urt — APPROVED** [review]

File: src/components/ADempiere/Report/Data/DataReport.vue [hunk 1]
```diff
@@ -597,6 +597,13 @@ export default defineComponent({
 </script>
 
 <style>
+.el-table .el-icon-arrow-right:before {
```
Comment (EdwinBetanc0urt) [inline src/components/ADempiere/Report/Data/DataReport.vue]: By not having a different or unique parent class for this component, and the `style` tag not having the `scope` property, the style change may affect other tables where the `.el-icon-arrow-right` class is used, in case a report is loaded first and then a window, smart query or form with table is opened.


Please set a unique class to the root tag of the component and place the style tag as scss:
```html
<style lang=“scss”>
.unique-class-to-root {
  .el-table .el-icon-arrow-right-right:before {
    // code
  }
}
</style>
```

Or just add the `scope` property `<style scope>` but sometimes it generates unexpected behavior with classes that are global like `.el-table`.

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]

**Review by EdwinBetanc0urt — APPROVED** [review]
