### PR TITLE
Validate POS

### LINKED ISSUE #2712: Demora en operación desde Punto de Venta
## Bug report

Se encuentran demoras en la utilización del Punto de ventas en cuanto a la creación de líneas y definición de Cantidades

image

Tiempo atrás esto se manejó en las issues: solop-develop/vue-1.0#1815 

Se resolvió moviendo este cliente y trayendolo a un datacenter local ya que al parecer con menos latencia este tiempo se veía notoriamente mejorado.

#### Screenshot or Gif（截图或动态图）

https://github.com/user-attachments/assets/bfad4a35-84ea-4cd8-b2e2-b9731af4e349

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

image

### PR DESCRIPTION
**Pull request by elsiosanchez**
#### Screenshot or Gif

https://github.com/user-attachments/assets/5f3a775b-45ad-4faa-8358-983c52383ca9

fixes https://github.com/solop-develop/frontend-core/issues/2712

### CODE REVIEW

File: src/store/modules/ADempiere/form/VPOS/index.js [hunk 1]
```diff
@@ -91,15 +91,6 @@ export default {
       return new Promise(resolve => {
         const currentRouter = router.app.$route
         const { posId } = currentRouter.query
-        if (isEmptyValue(posId)) {
```
Comment (yamelsenih) [inline src/store/modules/ADempiere/form/VPOS/index.js:94]: This is unnecessary

**Review by yamelsenih — CHANGES_REQUESTED** [review]
This is unnecessary

File: src/store/modules/ADempiere/form/VPOS/index.js (hunk 1 above)
Comment (elsiosanchez) [reply src/store/modules/ADempiere/form/VPOS/index.js:94]: Yes, that's why I deleted it.

**Review by EdwinBetanc0urt — APPROVED** [review]
