### PR TITLE
Fix: Version Dictionary RS

### LINKED ISSUE #2336: Agregar soporte para ver la versión de `Dictionary RS`
#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）
image

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

### PR DESCRIPTION
**Pull request by Ricargame**
#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif
image

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- Yarn version:
- adempiere-vue version: 

#### Additional context
fixed: https://github.com/solop-develop/frontend-core/issues/2336

### CODE REVIEW

File: src/lang/ADempiere/es/index.js [hunk 1]
```diff
@@ -236,7 +236,8 @@ export default {
       dateVersion: 'Fecha Versión',
       frontEndVersion: 'Versión del Front-End',
       proxyVersion: 'Versión del Proxy',
-      deploymentName: 'Nombre de Implementación'
+      deploymentName: 'Nombre de Implementación',
+      srVersion: 'Versión del Dictionary RS'
```
Comment (EdwinBetanc0urt) [inline src/lang/ADempiere/es/index.js]: please change `srVersion` key to `dictionaryVersion`

File: src/lang/ADempiere/en/index.js [hunk 2]
```diff
@@ -235,7 +235,8 @@ export default {
       dateVersion: 'Date Versión',
       frontEndVersion: 'Front-End Version',
       proxyVersion: 'Proxy Version',
-      deploymentName: 'Deployment Name'
+      deploymentName: 'Deployment Name',
+      srVersion: 'RS dictionary version'
```
Comment (EdwinBetanc0urt) [inline src/lang/ADempiere/en/index.js]: please change `srVersion` key to `dictionaryVersion`

File: src/api/ADempiere/common/index.ts [hunk 3]
```diff
@@ -51,6 +51,16 @@ export function systemInfo() {
     })
 }
 
+export function systemInfoDictionaryRs() {
+  return request({
+    url: '/dictionary/system-info',
+    method: 'get'
+  })
+    .then(response => {
+      return camelizeObjectKeys(response)
```
Comment (EdwinBetanc0urt) [inline src/api/ADempiere/common/index.ts]: please remove `camelizeObjectKeys`.

File: src/store/modules/user.js [hunk 4]
```diff
@@ -76,7 +77,8 @@ const state = {
   sessionInfo: {},
   corporateBrandingImage: '',
   activityLogs: [],
-  systemInfo: {}
+  systemInfo: {},
+  srVersion: {}
```
Comment (EdwinBetanc0urt) [inline src/store/modules/user.js]: please change `srVersion` key to `dictionary`

File: src/views/profile/components/InfoUser.vue [hunk 5]
```diff
@@ -403,6 +421,8 @@ export default defineComponent({
       }
     })
 
+    const rsVersion = store.getters['user/getSrVersion']
+    console.log(store.getters['user/getSrVersion'])
```
Comment (EdwinBetanc0urt) [inline src/views/profile/components/InfoUser.vue]: please remove this console.log

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]

**Review by EdwinBetanc0urt — APPROVED** [review]
