### PR TITLE
Fix: Line Currency does not Respect head Currency

### LINKED ISSUE #2940: moneda en líneas no respeta moneda de cabezal
## Datos de Sesión
- Compañía: Solop
- Rol: Administrador
- Puerto: 24814
- Versión: 023
- Host / Servidor: SPDEV02 
- Opción de Menú: Ordenes de Compra

### Pasos para Reproducir

1. crear orden de compra en USD
2. Crear línea. ver moneda antes de guardar
3. ver moneda despues de guardar

### Print de Pantalla o Video

https://github.com/user-attachments/assets/2d10e770-94d2-4145-8acd-8351f65a5da8

### PR DESCRIPTION
**Pull request by elsiosanchez**
#### Screenshot or Gif

https://github.com/user-attachments/assets/c4328092-f59a-4c9f-afa7-1cafb5ad5363

fixes #2940

### CODE REVIEW

File: src/components/ADempiere/FieldDefinition/FieldNumber.vue [hunk 1]
```diff
@@ -197,7 +197,7 @@ export default {
 
       const value = this.$store.getters.getValueOfField({
```
Comment (EdwinBetanc0urt) [inline src/components/ADempiere/FieldDefinition/FieldNumber.vue:198]: Please validate first with `containerUuid` and validate after with `firstTabUuid`.

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]
