### PR TITLE
Fix: Parse date in grid mode

### LINKED ISSUE #2326: Ventanas: Fecha en modo Grilla muestra siempre Fecha+Hora
## Bug report
Pese a que un campo esté definido como sólo "FECHA" en modo grilla siempre está mostrando tabmién la HORA

image

En Modo Mono Registro está ok

image

En System está definido como DATE el campo

image

#### Steps to reproduce

1. Abrir Ventana "Proyectos"
2. Modo grilla ver campo "Contract Date"
3. Modo Mono ver campo "Contract Date" 

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: 3.9.9

### PR DESCRIPTION
**Pull request by elsiosanchez**
#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif

Image

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- Yarn version:
- adempiere-vue version:

### CODE REVIEW

File: src/utils/ADempiere/valueFormat.js [hunk 1]
```diff
@@ -97,7 +97,11 @@ export function formatField({
       formattedValue = formatDateTemp({
         value,
         isTime: false,
-        format: optionalFormat
+        format: getDateFormat({
+          format: 'YYYY-MM-DD',
```
Comment (EdwinBetanc0urt) [inline src/utils/ADempiere/valueFormat.js]: Please validate format by context

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]

**Review by EdwinBetanc0urt — APPROVED** [review]
