### PR TITLE
Fix: Improve Workflow Activity Viewer

### LINKED ISSUE #654: Cambiar la visual de la ventana para que sea más amigable a ver desde un móvil: Pasar todo a una columna en vez de 2 como está ahora, de manera que haciendo Scroll se logra ver todo.
Actualmente desde un Móvil se ve así:
image

Cambiar el orden de los campos:

1. Bitácora de cambios
2. Acción
3. Flujo de trabajo visual (dejar de alguna manera oculto para que no se vea siempre, sólo si se desea se abre la sección y se visualiza)

### PR DESCRIPTION
**Pull request by elsiosanchez**
### _**GIF**_

https://user-images.githubusercontent.com/45974454/207082972-56fe1574-254a-4b52-8ab0-1d6e9365f372.mp4

### _**ISSUE**_

Fixes https://github.com/solop-develop/frontend-core/issues/654

### CODE REVIEW

File: src/layout/components/AppMain.vue [hunk 1]
```diff
@@ -1,11 +1,11 @@
 <template>
-  <section id="appMain" class="app-main">
-    <transition name="fade-transform" mode="out-in">
-      <keep-alive :include="cachedViews">
-        <router-view :key="key" />
-      </keep-alive>
-    </transition>
-  </section>
+  <!-- <div id="appMain" class="app-main"> -->
+  <transition id="brazil" name="fade-transform" mode="out-in">
```
Comment (EdwinBetanc0urt) [inline src/layout/components/AppMain.vue]: @elsiosanchez justifies these changes

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]

File: src/layout/components/AppMain.vue [hunk 2]
```diff
@@ -1,11 +1,11 @@
...
-  <section id="appMain" class="app-main">
-    <transition name="fade-transform" mode="out-in">
-      <keep-alive :include="cachedViews">
-        <router-view :key="key" />
-      </keep-alive>
-    </transition>
-  </section>
+  <!-- <div id="appMain" class="app-main"> -->
+  <transition name="fade-transform" mode="out-in">
+    <keep-alive id="casemiro" :include="cachedViews">
```
Comment (EdwinBetanc0urt) [inline src/layout/components/AppMain.vue]: @elsiosanchez justifies these changes

File: src/layout/components/AppMain.vue [hunk 3]
```diff
@@ -1,11 +1,11 @@
...
+      <router-view id="neymar" :key="key" />
```
Comment (EdwinBetanc0urt) [inline src/layout/components/AppMain.vue]: @elsiosanchez justifies these changes

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]

**Review by EdwinBetanc0urt — APPROVED** [review]
