### PR TITLE
Fix: Zoom Report

### LINKED ISSUE #2680: [Bug Report] Redundancia Acercador de Reporte
## Bug report
se requeire que en caso de que tenga 2 ventanas filtrar la ventana que tenga is_sales_transaction igual al valor del campo IsSOTrx

#### Screenshot or Gif（截图或动态图）

image

### PR DESCRIPTION
**Pull request by elsiosanchez**
#### Screenshot or Gif

https://github.com/user-attachments/assets/38be3d05-dd4c-4c65-8b2f-22cb81691e14

fixes https://github.com/solop-develop/frontend-core/issues/2680

### CODE REVIEW

File: src/components/ADempiere/Report/Data/DataCells.vue [hunk 1]
```diff
@@ -231,13 +232,31 @@ export default defineComponent({
...
+          if (listZoom.length > 1) {
+            listZoom = zoom_windows.filter(zoom => {
+              const {
+                uuid,
+                tab_uuid,
+                is_sales_transaction
+              } = zoom
+              const salesTransaction = Boolean(isSalesTransaction({
+                parentUuid: uuid,
+                containerUuid: tab_uuid
```
Comment (EdwinBetanc0urt) [inline src/components/ADempiere/Report/Data/DataCells.vue]: on containerUuid change tab_uuid by report UUID.

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]
