### PR TITLE
fix: Advanced Project Search

### LINKED ISSUE #2428: Busqueda avanzada Proyecto por Estado de Proyecto no aparecen valores
## Bug report

Se intenta hacer una búsqueda avanzada desde la ventana "Orden de Trabajo" (lo mismo pasa con ventana Proyectos)

ZK
image

VUE
image

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/3be7233b-6ae8-4c87-9f66-33be8bda20bf

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:  4.1.3

Instancia 
http://spdev01.solopapp.com:24700/vue#/profile/index
http://spdev01.solopapp.com:24702/webui/index.zul

### PR DESCRIPTION
**Pull request by Ricargame**
#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif

https://github.com/user-attachments/assets/4ce98a54-66b6-4502-a13b-cdbf669aacbb

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- Yarn version:
- adempiere-vue version: 

#### Additional context
fixed: https://github.com/solop-develop/frontend-core/issues/2428

### CODE REVIEW

File: src/components/ADempiere/FieldDefinition/FieldSelect/index.vue [hunk 1]
```diff
@@ -368,8 +368,6 @@ export default {
       })
     },
     loadListFromServer(searchQuery = '') {
-      this.isLoading = true
```
Comment (EdwinBetanc0urt) [inline src/components/ADempiere/FieldDefinition/FieldSelect/index.vue:371]: What is the reason for changing these lines?

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]

**Review by EdwinBetanc0urt — APPROVED** [review]
