### PR TITLE
Fix: Consider Fields In Export

### LINKED ISSUE #2416: Descargar Registros Seleccionados desde Ventana no considera campo
## Bug report

Tenemos un tema raro q no me había percatado antes.
Descargamos a excel registros seleccionados en una ventana y hay un campo (Agente comercial) que no lo agrega en el Excel y no le encuentro explicación.

[Orden de Trabajo 2024-06-21 9_5_9.xlsx](https://github.com/user-attachments/files/16128964/Orden.de.Trabajo.2024-06-21.9_5_9.xlsx)

#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif（截图或动态图）

https://github.com/solop-develop/frontend-core/assets/31936815/68097b43-0d93-435b-8d09-57d27c204847

image

image

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

### PR DESCRIPTION
**Pull request by Ricargame**
#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Screenshot or Gif

https://github.com/solop-develop/frontend-core/assets/78000356/b41fc23e-0621-4a7b-8e4d-4ef0ea4d45e2

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- Yarn version:
- adempiere-vue version: 

#### Additional context
fixed: https://github.com/solop-develop/frontend-core/issues/2416

### CODE REVIEW

File: src/utils/ADempiere/exportUtil.js [hunk 1]
```diff
@@ -184,27 +184,17 @@ export const exportRecords = ({ parentUuid, containerUuid, containerManager, for
...
-      !isEmptyValue(is_displayed) &&
-      !isEmptyValue(is_displayed_grid) &&
-      !(is_displayed && is_displayed_grid)
-    ) {
-      return false
-    }
-    // Hide encrypted fields
-    if (is_encrypted) {
+    // Hide simple button fields without a value
+    if (!fieldItem.isShowedTableFromUser) {
```
Comment (EdwinBetanc0urt) [inline src/utils/ADempiere/exportUtil.js]: please change to `containerManager.isDisplayedColumn(fieldItem)`

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]

File: src/utils/ADempiere/exportUtil.js [hunk 2]
```diff
@@ -184,41 +184,35 @@ export const exportRecords = ({ parentUuid, containerUuid, containerManager, for
...
-      !isEmptyValue(is_displayed) &&
-      !isEmptyValue(is_displayed_grid) &&
-      !(is_displayed && is_displayed_grid)
-    ) {
-      return false
-    }
-    // Hide encrypted fields
-    if (is_encrypted) {
-      return false
+    const shoUser = fieldItem.isShowedTableFromUser
```
Comment (EdwinBetanc0urt) [inline src/utils/ADempiere/exportUtil.js]: please rename this variable to `isShowUser`.

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]

**Review by EdwinBetanc0urt — APPROVED** [review]
