### PR TITLE
Fix: Accounting Entry Line

### LINKED ISSUE #2780: Líneas de Asiento desde Ventana del Documento
## Bug report

Se desea pode visualizar de una manera más prolija y concreta los asientos desde las ventanas de los documentos.

Actualmente se está visualizando de esta manera 
image

En un reporte se ve asi

image

Diría de ponerle este mismo formato que está en los reportes.
Ver si vale la pena ponerle 1 tamaño más grande tal como se solicitó en los reportes.

Por otro lado, se desea visualizar de una manera más clara el asiento desde la ventana y creo que las siguientes modificaciones podrían ayudar:

1. Ampliar el espacio de mostrar el asiento bajando la barra del scroll horizontal para el final de la página bien abajo.
2. Bajar los botones para la parte bien baja de la ventana
3. Ampliar el ancho de la columna de la cuenta contable
4. Agregar el Nro de cuenta antes del nombre "12110 - Cuentas por Cobrar Comerciales" 

image

Ej así podría qeudar el ancho de las columnas

image

ver como está en ZK que es un poco la idea que sugiero

image

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

### PR DESCRIPTION
**Pull request by Ricargame**
#### Screenshot or Gif

https://github.com/user-attachments/assets/37f279cb-1900-4c3f-9508-2d3938875210

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- Yarn version:
- adempiere-vue version: 

#### Additional context
fixes: https://github.com/solop-develop/frontend-core/issues/2780

### CODE REVIEW

File: src/components/ADempiere/Form/AcctViewer/QueryCriteria/index.vue [hunk 1]
```diff
@@ -94,3 +94,9 @@ export default defineComponent({
   }
 })
 </script>
+
+<style>
+.box-card .el-divider--horizontal {
```
Comment (EdwinBetanc0urt) [inline src/components/ADempiere/Form/AcctViewer/QueryCriteria/index.vue]: once this style is loaded it will affect other places where the `el-card` component is used.

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]

**Review by EdwinBetanc0urt — APPROVED** [review]
